---
version: "2.4"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      TZ: Africa/Nairobi
      PUID: 1001
      PGID: 1000
      VERSION: docker
    volumes:
      - "/dev/shm:/transcode"
      - "/docker/plex/container/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/srv/mergerfs/multimedia/multimedia/entertainment:/multimedia/media1/entertainment"
    devices:
      - "/dev/dri:/dev/dri"
    restart: unless-stopped

  proxy:
    build:
      context: nginx
    container_name: plex-proxy
    healthcheck:
      test: curl --fail http://localhost/healthz || exit 1  
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 3s
    ports:
      - '32400:32400'
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    depends_on:
      - plex